
import javax.swing.JOptionPane;
import javax.swing.Icon;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

public class TRAGA extends javax.swing.JFrame {
int monedas = 20;

    /**
     * Creates new form NewJFrame
     */
    public TRAGA() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btJugar = new javax.swing.JButton();
        btJugar1 = new javax.swing.JButton();
        lbmonedas = new javax.swing.JLabel();
        lb1 = new javax.swing.JLabel();
        lb2 = new javax.swing.JLabel();
        lb3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MAQUINA TRAGAMONEDAS");

        btJugar.setBackground(new java.awt.Color(204, 204, 204));
        btJugar.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btJugar.setText("GIRAR");
        btJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btJugarActionPerformed(evt);
            }
        });

        btJugar1.setBackground(new java.awt.Color(204, 204, 204));
        btJugar1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btJugar1.setText("DEVOLVERSE");
        btJugar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btJugar1ActionPerformed(evt);
            }
        });

        lbmonedas.setBackground(new java.awt.Color(0, 0, 0));
        lbmonedas.setFont(new java.awt.Font("Rockwell Condensed", 0, 24)); // NOI18N
        lbmonedas.setForeground(new java.awt.Color(255, 255, 255));
        lbmonedas.setText("DINERO:");

        lb1.setText("jLabel2");

        lb2.setText("jLabel2");

        lb3.setText("jLabel2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbmonedas, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btJugar, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(128, 128, 128)
                        .addComponent(btJugar1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(115, 115, 115))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lb1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(lb2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                        .addComponent(lb3, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(136, 136, 136))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(261, 261, 261))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lb3)
                            .addComponent(lb1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE))
                        .addGap(152, 152, 152))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lb2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btJugar1)
                            .addComponent(btJugar)
                            .addComponent(lbmonedas))
                        .addGap(61, 61, 61))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btJugarActionPerformed
       
        monedas -= 1;
        int fruta1 = (int)(Math.random()*16)*1;
        int fruta2 = (int)(Math.random()*16)*1;
        int fruta3 = (int)(Math.random()*16)*1;
        Icon manzana = new javax.swing.ImageIcon(getClass().getResource("/traga/manzana.jpg"));
        Icon cereza = new javax.swing.ImageIcon(getClass().getResource("/traga/cereza.jpg"));
        Icon campana = new javax.swing.ImageIcon(getClass().getResource("/traga/campana.jpg"));
        Icon bar = new javax.swing.ImageIcon(getClass().getResource("/traga/bar.jpg"));
        Icon cerrojo = new javax.swing.ImageIcon(getClass().getResource("/traga/cerrojo.jpg"));
        Icon corazon = new javax.swing.ImageIcon(getClass().getResource("/traga/corazon.jpg"));
        Icon diamante = new javax.swing.ImageIcon(getClass().getResource("/traga/diamante.jpg"));
        Icon mango = new javax.swing.ImageIcon(getClass().getResource("/traga/mango.jpg"));
        Icon moneda = new javax.swing.ImageIcon(getClass().getResource("/traga/moneda.jpg"));
        Icon naranja = new javax.swing.ImageIcon(getClass().getResource("/traga/naranja.jpg"));
        Icon pregunta = new javax.swing.ImageIcon(getClass().getResource("/traga/pregunta.jpg"));
        Icon sandia = new javax.swing.ImageIcon(getClass().getResource("/traga/sandia.jpg"));
        Icon siete = new javax.swing.ImageIcon(getClass().getResource("/traga/siete.jpg"));
        Icon trebol = new javax.swing.ImageIcon(getClass().getResource("/traga/trebol.jpg"));
        Icon uvas = new javax.swing.ImageIcon(getClass().getResource("/traga/uvas.jpg"));
        Icon berenjena = new javax.swing.ImageIcon(getClass().getResource("/traga/berenjena.jpg"));
        
        switch(fruta1){
                 case 0: lb1.setIcon(manzana);break;
                 case 1: lb1.setIcon(cereza);break;
                 case 2: lb1.setIcon(campana);break;
                 case 3: lb1.setIcon(bar);break;
                 case 4: lb1.setIcon(cerrojo);break;
                 case 5: lb1.setIcon(corazon);break;
                 case 6: lb1.setIcon(diamante);break;
                 case 7: lb1.setIcon(mango);break;
                 case 8: lb1.setIcon(moneda);break;
                 case 9: lb1.setIcon(naranja);break;
                 case 10: lb1.setIcon(pregunta);break;
                 case 11: lb1.setIcon(sandia);break;
                 case 12: lb1.setIcon(siete);break;
                 case 13: lb1.setIcon(trebol);break;
                 case 14: lb1.setIcon(uvas);break;
                 case 15: lb1.setIcon(berenjena);break;
                
             }
        switch(fruta2){
                 case 0: lb2.setIcon(manzana);break;
                 case 1: lb2.setIcon(cereza);break;
                 case 2: lb2.setIcon(campana);break;
                 case 3: lb2.setIcon(bar);break;
                 case 4: lb2.setIcon(cerrojo);break;
                 case 5: lb2.setIcon(corazon);break;
                 case 6: lb2.setIcon(diamante);break;
                 case 7: lb2.setIcon(mango);break;
                 case 8: lb2.setIcon(moneda);break;
                 case 9: lb2.setIcon(naranja);break;
                 case 10: lb2.setIcon(pregunta);break;
                 case 11: lb2.setIcon(sandia);break;
                 case 12: lb2.setIcon(siete);break;
                 case 13: lb2.setIcon(trebol);break;
                 case 14: lb2.setIcon(uvas);break;
                 case 15: lb2.setIcon(berenjena);break;
                 
                 }
        switch(fruta3){
                 case 0: lb3.setIcon(manzana);break;
                 case 1: lb3.setIcon(cereza);break;
                 case 2: lb3.setIcon(campana);break;
                 case 3: lb3.setIcon(bar);break;
                 case 4: lb3.setIcon(cerrojo);break;
                 case 5: lb3.setIcon(corazon);break;
                 case 6: lb3.setIcon(diamante);break;
                 case 7: lb3.setIcon(mango);break;
                 case 8: lb3.setIcon(moneda);break;
                 case 9: lb3.setIcon(naranja);break;
                 case 10: lb3.setIcon(pregunta);break;
                 case 11: lb3.setIcon(sandia);break;
                 case 12: lb3.setIcon(siete);break;
                 case 13: lb3.setIcon(trebol);break;
                 case 14: lb3.setIcon(uvas);break;
                 case 15: lb3.setIcon(berenjena);break;
                
                 }
             
        if(fruta1==fruta2&&fruta2==fruta3){
            switch(fruta1){
                case 0:
                    monedas+=30+1;
                JOptionPane.showMessageDialog(this,"Ganaste 30 monedas");
                break;
                case 1:
                monedas+=50+1;
                JOptionPane.showMessageDialog(this,"Ganaste 50 monedas");
                break;
                case 2:
                    monedas+=100+1;
                    JOptionPane.showMessageDialog(this,"Ganaste 100 monedas");
                    break;
                    case 3:
                    monedas+=10+1;
                    JOptionPane.showMessageDialog(this,"Ganaste 10 monedas");
                    break;
                    case 4:
                    monedas+=20+1;
                    JOptionPane.showMessageDialog(this,"Ganaste 20 monedas");
                    break;
                    case 5:
                    monedas+=40+1;
                    JOptionPane.showMessageDialog(this,"Ganaste 40 monedas");
                    break;
                    case 6:
                    monedas+=60+1;
                    JOptionPane.showMessageDialog(this,"Ganaste 60 monedas");
                    break;
                    case 7:
                    monedas+=70+1;
                    JOptionPane.showMessageDialog(this,"Ganaste 70 monedas");
                    break;
                    case 8:
                    monedas+=80+1;
                    JOptionPane.showMessageDialog(this,"Ganaste 80 monedas");
                    break;
                    case 9:
                    monedas+=90+1;
                    JOptionPane.showMessageDialog(this,"Ganaste 90 monedas");
                    break;
                    case 10:
                    monedas+=1000+1;
                    JOptionPane.showMessageDialog(this,"Ganaste 1000 monedas");
                    break;
                    case 11:
                    monedas+=500+1;
                    JOptionPane.showMessageDialog(this,"Ganaste 500 monedas");
                    break;
                    case 12:
                    monedas+=150+1;
                    JOptionPane.showMessageDialog(this,"Ganaste 150 monedas");
                    break;
                    case 13:
                    monedas+=130+1;
                    JOptionPane.showMessageDialog(this,"Ganaste 130 monedas");
                    break;
                    case 14:
                    monedas+=5000+1;
                    JOptionPane.showMessageDialog(this,"Ganaste 5000 monedas");
                    break;
                    case 15:
                    monedas+=250+1;
                    JOptionPane.showMessageDialog(this,"Ganaste 250 monedas");
                    break;
                
            }
        }
        
        lbmonedas.setText("MONEDAS "+String.valueOf(monedas));
        if(monedas == 0){
        int numero = JOptionPane.showConfirmDialog(this,"quieres jugar de nuevo","maquina tragamonedas",JOptionPane.YES_NO_OPTION);
        if(numero == 0){
            monedas = 20;
            lbmonedas.setText("MONEDAS "+String.valueOf(monedas));
            }else{
            System.exit(0);
        }
        

    }//GEN-LAST:event_btJugarActionPerformed
    }
    private void btJugar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btJugar1ActionPerformed
dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btJugar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TRAGA().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btJugar;
    private javax.swing.JButton btJugar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lb1;
    private javax.swing.JLabel lb2;
    private javax.swing.JLabel lb3;
    private javax.swing.JLabel lbmonedas;
    // End of variables declaration//GEN-END:variables
}
